### ISSUE TITLE
Printing with a shared Zebra printing

### ISSUE THREAD

**Issue by BryanJ-97** [rkone/sharpzebra#18]
Hey body, I'm using your library and I have a little issue about it.
I'm trying to print with a shared printer Zebra but I don't know which type of connection should I have to use
or can you help me with any tutorial or example using these library? it''ll be great!!

**Comment by rkone** [comment]
If it's not a network printer, it will need to be installed on the local machine (you can install a remotely shared printer though).
Then the tutorial on the wiki link prints to an installed printer:
https://github.com/rkone/sharpzebra/wiki

**Comment by BryanJ-97** [comment]
Thanks a lot for your help.....
