### ISSUE TITLE
Nuget and Readme

### ISSUE THREAD

**Issue by marcosgerene** [rkone/sharpzebra#20]
There are two packages at NuGet Gallery:

https://www.nuget.org/packages/SharpZebra.rkone/

https://www.nuget.org/packages/SharpZebraStandard/

Which is correct?

PS: It could be interesting to add a Readme to the project with those kinds of information.

**Comment by rkone** [comment]
Hi Marcos,

The dependencies are different.  It's kind of clear from the name of the packages I thought?
________________________________
From: Marcos Gerene F. Spirito ***@***.***>
Sent: Tuesday, May 18, 2021 9:30 AM
To: rkone/sharpzebra ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rkone/sharpzebra] Nuget and Readme (#20)


There are two packages at NuGet Gallery:

https://www.nuget.org/packages/SharpZebra.rkone/

https://www.nuget.org/packages/SharpZebraStandard/

Which is correct?

PS: It could be interesting to add a Readme to the project with those kinds of information.

**Comment by marcosgerene** [comment]
@rkone  It is. Actually, I am just making sure of that.

About the read-me, have you thought about that?

Tks

**Comment by rkone** [comment]
I think the wiki here is fine, I've never browsed descriptions on nuget.org, and mostly there's none there!
Thanks for the suggestion.
