### ISSUE TITLE
Using sharpzebra on net 7.0

### ISSUE THREAD

**Issue by dev-rizky** [rkone/sharpzebra#24]
Hi, is it possible to use this lib on net 7.0 project? And can you help me to show a documentation to use this library? thank you

**Comment by rkone** [comment]
Sure it will work.  Check the wiki link for some quick start steps.

________________________________
From: Rizky Accelist ***@***.***>
Sent: Monday, September 4, 2023 12:37 AM
To: rkone/sharpzebra ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rkone/sharpzebra] Using sharpzebra on net 7.0 (Issue #24)


Hi, is it possible to use this lib on net 7.0 project? And can you help me to show a documentation to use this library? thank you

**Comment by dev-rizky** [comment]
Can you provide me the wiki link? I am using zebra Zt411 with usb connection. Thanks

**Comment by rkone** [comment]
https://github.com/rkone/sharpzebra/wiki

________________________________
