### ISSUE TITLE
How can I set Label size in mm Unit ?

### ISSUE THREAD

**Issue by PttTaiwan** [rkone/sharpzebra#25]
Hi, thank for your perfect library !!!
I am new to zebra label , I have seen your project Wiki, but I can not  sure how to setup the label size in my code correctly.
In my project, I need to print the label on thermal label (90mm * 45mm) by using GODEX-G500 printer (203 dpi).
[zLabelQ1](https://github.com/rkone/sharpzebra/assets/62923635/9431c529-1cc4-4388-a0c9-66833a10e00d)
Since,  PrinterSettings.Width &  PrinterSettings.Height is Integer, I set the variables like below
![zLabelQ2](https://github.com/rkone/sharpzebra/assets/62923635/af38da29-1272-4d8a-b855-9a2bf01e505d)
but I have noticed in your wiki (Width and height are set in dots,), Now I am confused, can you help me or give me the example ?
Many thanks!
:)

**Comment by rkone** [comment]
By definition,.dpi is dots per inch.  So you have set 203 dpi * 9 inches to get the width in your sample..
For mm use 203 dpi / 25.4 mm per inch = 8 dots per mm instead. So your label size is 90*8 by 45*8 dots

**Comment by PttTaiwan** [comment]
Dear rkone,
thanks for your reply, now I have modify my code to  p.Width = 90 * 8 &  p.Length = 45 * 8.
many thanks.
