### ISSUE TITLE
Sharpzebra.dll and Windows 10

### ISSUE THREAD

**Issue by nilsarve** [rkone/sharpzebra#3]
Hello

Are trying your dll with Zebra KR403 printer. Works fine with windows 7 but cant get status to work with windows 10. Printing works though. 

I am using labview and it is the UsbPrinterConnector that gives an error i belive. 

Error message:
Error: 1172 Error creating instance of UsbPrinterConnector in assembly Com.SharpZebra.Printing.UsbPrinterConnector, Com.SharpZebra, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null, (System.Exception: Cannot locate USB device )

**Comment by rkone** [comment]
Do you have the same issue if you set your solution to target x86?

**Comment by nilsarve** [comment]
Thank you for answering!

I was using your precompiled dll from codeplex.

Do I need Visual studio 2017 to build this solution?


Vennlig hilsen/Best regards

*Nils Arve Hyldbakk*

/Technology development engineer/

……………………………………………………

Tlf: 92 85 59 74

Web: www.el-watch.com <http://www.el-watch.com/>

……………………………………………………

Logo_El-Watch_landscape_epost
Den 31.10.2017 16:04, skrev rkone:

**Comment by rkone** [comment]
It should be sufficient to compile your solution that uses the precompiled sharpzebra dll, but set the target solution platform to x86.

**Comment by nilsarve** [comment]
I use your dll with Labview and there is no option to compile my Labview application to x86 but I guess it is x86 by default. Tried running my application with XP compatibility but no change.

**Comment by rkone** [comment]
Sorry, I'm not too familiar with LabVIEW.  I thought you using this library an application you created.

I see LabVIEW comes in x86 and x64 versions.  Can you make sure you're using the x86 version of LabVIEW? 

Is the printer connected with both USB and network? It's weird you can print but status crashes.. Unless you're printing with it setup as a NetworkPrinter but getting status from it as a USBPrinter (which would make some sense, as you can't get the status through NetworkPrinter)

**Comment by nilsarve** [comment]
It's the x86 version of labview. The printer is only connected with USB. 

Yeah it's weird printing is ok but not status.

**Comment by rkone** [comment]
I think you'll have to provide the code you use to print as well as the code used to get the printer status.

Are you able to check that you're using the same driver on Windows 10 as you were using on win7?

**Comment by nilsarve** [comment]
Still struggling to get this working.
Same driver on win7 and win10.
To print in labview: (working on both win7 and win10)
![image](https://user-images.githubusercontent.com/7568806/35557413-5dee6546-05a5-11e8-8f30-402f3c8d50e8.png)

**Comment by nilsarve** [comment]
Requesting printer status: (working on win7 but not windows 10)
![image](https://user-images.githubusercontent.com/7568806/35557932-e7091262-05a6-11e8-9a4a-93e796b09290.png)

**Comment by rkone** [comment]
It looks as though this is related with issue #6 - it seems USB Printing in windows 10 has changed.  I will look into this when I get a chance. The main problem is I don't actually have USB printers available to test with at the moment.

**Comment by nilsarve** [comment]
I can help you test your new code if you got an idea how to fix it.

**Comment by rkone** [comment]
The GitHub code has a fix for this issue. I'm working on updating the NuGet packages now.

**Comment by nilsarve** [comment]
It would be great if you could publish this new version as a dll?

**Comment by rkone** [comment]
It's certainly .NET. Maybe labview is only compatible with older versions of .NET?  The latest sharpzebra is using 4.5.2

**Comment by nilsarve** [comment]
You are probably right about labview not being compatible with .NET 4.5.2. 
Sorry for the hassle but do you have the time to build the newest version with .NET 2.0 framework?

**Comment by rkone** [comment]
[SharpZebraTest.zip](https://github.com/rkone/sharpzebra/files/2142412/SharpZebraTest.zip)
Try this.

**Comment by nilsarve** [comment]
That worked! Thank you! 
Very nice of you to help me with this! 
I owe you one!

**Comment by KunalSati** [comment]
hello, 
I am new to Labview, I saw your threads above and the snip image of the VI. can you please help how to the "ZPLCommands" node/icon (i.e. the VI block) and how to use your SharpZebra .dll with it.

I am trying to print sticker labels from Zebra ZT410  printer.

Thanks in advance

**Comment by rkone** [comment]
I really don't know anything about LabVIEW. Maybe @nilsarve  can help you?

**Comment by nilsarve** [comment]
Hello @KunalSati 
On the labview block diagram you go to communication and .NET.  Select the .NET Constructor  and browse to the SharpZebraTest.dll you can download from this thread. Under Com.SharpZebra.Commands you find ZPLCommands. 

Then follow the above .vi pictures to print and get status.

**Comment by sandhya-assaabloy** [comment]
Hello Nilsarve,
i did tried above code in labview, but not able to communicate. Need you help

**Comment by Juancho-Coding** [comment]
I'm using the library with labview but I use the SpoolPrinter class, it works on Labview2018 and windows 10
