### ISSUE TITLE
Minor bug or working as designed?

### ISSUE THREAD

**Issue by anubi** [rkone/sharpzebra#4]
If you call ZPLCommands.CustomStringWrite() before you call ClearPrinter(), PrinterSettings will always be null and CustomStringWrite will fail! Should CustomString's constructor not create an empty PrinterSettings when instantiated? Or is it intended you must always call ClearPrinter() before doing any work?

I'm using the library just for generating ZPL-compliant text from an image, so settings don't apply for me necessarily.

**Comment by rkone** [comment]
Well, it's outside the intended use at least.  I can make it friendlier to use.

**Comment by rkone** [comment]
CustomStringWrite now contains an additional parameter - ramDrive. This will default to R (and not crash) if left blank. Specifying PrinterSettings is no longer necessary (but will still be used if specified).
