### ISSUE TITLE
Print should return success or failure.

### ISSUE THREAD

**Issue by prasadghole** [rkone/sharpzebra#5]
For spool printer we are ignoring success status obtained from SengBytesToPrinter function.

**Comment by rkone** [comment]
Changing the interface definition for spool printer means we'd also have to return a value for NetworkPrinter which has no idea if the network data gets to the printer.

I could change Print to return a bool? - this is somewhat more useful I guess..  I will think about it.

**Comment by prasadghole** [comment]
Yes. I would like if we print can return bool. But as this is base interface for all the modules will impact all the higher level implementation of Print Interface.

**Comment by rkone** [comment]
The latest version now returns bool? 
NetworkPrinters always return null while USB and Spool printers will return true/false.
