### ISSUE TITLE
win 10 don't exist SymbolicLink item

### ISSUE THREAD

**Issue by zhangfl0220** [rkone/sharpzebra#6]
path = subKey.GetValue("SymbolicLink").ToString(); 
throw an error.

Can you fix it in Win10?

**Comment by rkone** [comment]
I don't have a USB printer available to test with now. Can you paste your registry data for the SYSTEM\CurrentControlSet\Control\DeviceClasses\{guid}\##?#USB#VID_0A5F* key?

**Comment by macleo** [comment]
same with me， under win10 can't using 
----------------------------------------
            //TODO: Query registry for specific printer only instead of enumeration.
            Dictionary<string, string> plist = EnumDevices();
            if (plist.ContainsKey(PrinterName))
                this.interfaceName = plist[PrinterName];
            else
                throw new Exception("Cannot locate USB device");
----------------------------------------------------------------------------------
Will u fix it?thx

**Comment by macleo** [comment]
![capture](https://user-images.githubusercontent.com/1946539/35029522-45e9481c-fb96-11e7-9ecf-d6bb9e8d9f6e.PNG)
can't print Chinese. thx

**Comment by rkone** [comment]
Hi macleo,
I will update the EPL functions to support specifying the codepage for character encoding. It looks like you want to use 936 for Chinese (traditional is 950).
I will look into the win10 USB printing issue shortly.

**Comment by rkone** [comment]
I've shared a new version that fixes the USBPrinter issue.  Please open a new ticket if you encounter further issues.

**Comment by macleo** [comment]
thank you rkone， I pull try it.
